version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=datasearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.initial_master_nodes=elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.1
    ports:
      - "5601:5601"

volumes:
  esdata:
    driver: local
    driver_opts:
      device: D:\elasticsearch\data
      o: bind
      type: none

## nếu es ko chạy đc bị tự động chết và có log bootstrap checks failed
## dùng wsl chạy lệnh  wsl -d docker-desktop 
## sysctl -w vm.max_map_count=262144
